basePath: /v1
definitions:
  handlers.AddUserInput:
    properties:
      email:
        example: johndoe@example.com
        type: string
      image:
        example: https://example.com/image.png
        type: string
      name:
        example: John Doe
        type: string
      user_id:
        example: "1234567890"
        type: string
    type: object
  handlers.ServerInfo:
    properties:
      environment:
        type: string
      version:
        type: string
    type: object
  handlers.ServerStatus:
    description: Response for the health check
    properties:
      status:
        description: Status is the health status of the service
        type: string
      system_info:
        allOf:
        - $ref: '#/definitions/handlers.ServerInfo'
        description: SystemInfo contains information about the system
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      image:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
  problem.Problem:
    type: object
info:
  contact:
    email: nishojib@kupolog.com
    name: nishojib
    url: https://api.kupolog.com/support
  description: This is an API for the Kupolog app.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  termsOfService: https://api.kupolog.com/terms
  title: Swagger Kupolog API
  version: "1.0"
paths:
  /health:
    get:
      description: Checks the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ServerStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/problem.Problem'
      summary: Health check
      tags:
      - health
  /users:
    post:
      consumes:
      - application/json
      description: add by json user
      parameters:
      - description: Add user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.AddUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            properties:
              user:
                $ref: '#/definitions/models.User'
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            properties:
              errors:
                properties:
                  email:
                    type: string
                  image:
                    type: string
                  name:
                    type: string
                  user_id:
                    type: string
                type: object
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      summary: Add an user
      tags:
      - users
swagger: "2.0"
