name: Backend Fly Deploy

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy backend app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only --build-arg DB_DSN=$DB_DSN --build-arg API_URL=$API_URL --build-arg AUTH_SECRET=$AUTH_SECRET
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.BACKEND_FLY_API_TOKEN }}
          DB_DSN: ${{ secrets.DB_DSN }}
          API_URL: ${{ vars.API_URL}}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
