name: Deploy to Railway

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install packages
        working-directory: ./client
        run: npm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Link to railway project
        working-directory: ./client
        run: railway link ${{ secrets.RAILWAY_PROJECT_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy
        working-directory: ./client
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
