name: ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  style:
    name: API Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Format code
        working-directory: ./client
        run: npm run format

      - name: Lint code
        working-directory: ./client
        run: npm run lint:fix
