name: ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  style:
    name: Frontend Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --include=dev

      - name: Format code
        working-directory: ./frontend
        run: npm run format

      - name: Lint code
        working-directory: ./frontend
        run: npm run lint:fix
